message:
  correct-use: "&cCorrect use: /sic <item> <player>"
  item-received: "&aYou have received the item: %item%"
  item-received-console: "&a%player% received %item%"
  item-not-found: "&cItem not found: %item%"
  no-permission: "&cYou do not have permission for this command!"
  player-not-found: "&cPlayer not found!"
