name: SmartItemCreator
version: ${project.version}
main: it.moro.smartitem.SmartItemCreator
api-version: '1.13'
commands:
  smartitemcreator:
    description: Un comando di test
    usage: /smartitemcreator
    aliases: [sic, smartitem]