name: SmartItemCreator
version: ${project.version}
main: it.moro.smartitem.SmartItemCreator
api-version: '1.13'
commands:
  smartitemcreator:
    description: Command for give items
    usage: /smartitemcreator <item> <player>
    aliases: [sic, smartitem]

permissions:
  smartitemcreator.cmd:
    description: Permission for give items.
    default: op